name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  flutter_dotenv: ^5.2.1 #Para leer variables de entorno
  dio: ^4.0.6 #Para peticiones http
  flutter_riverpod: ^2.6.1 #Para manejar el estado
  card_swiper: ^3.0.1 #Para hacer el carrusel
  animate_do: ^3.0.2 #Para animaciones
  intl: ^0.20.2 #Para formatear fechas
  isar: ^3.1.0+1 #Para manejar la base de datos
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1 #Para manejar el almacenamiento
  flutter_staggered_grid_view: ^0.7.0 #Para hacer el carrusel
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1 #Para generar la base de datos pero solo en ambiente desarrollo
  build_runner: ^2.4.13 #Para generar la base de datos

flutter:
  uses-material-design: true
  assets:
   - .env
